# This rule is not used by the project crd itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the gdp.standardchartered.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: crd
    app.kubernetes.io/managed-by: kustomize
  name: gdptenant-editor-role
rules:
- apiGroups:
  - gdp.standardchartered.com
  resources:
  - gdptenants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gdp.standardchartered.com
  resources:
  - gdptenants/status
  verbs:
  - get
